### ISSUE TITLE
shrink needs a stopgap too

### ISSUE THREAD

**Issue by GoogleCodeExporter** [twak/campskeleton#1]
```
Hi,
Your OffsetSkeleton code appears to be broken. Running the attached file 
with the current source earns me a ClassCastException.

Exception in thread "main" java.lang.ClassCastException: 
straightskeleton.Edge cannot be cast to straightskeleton.Corner
     at straightskeleton.CornerClone.<init>(CornerClone.java:67)
     at straightskeleton.OffsetSkeleton.<init>(OffsetSkeleton.java:49)
     at straightskeleton.OffsetSkeleton.shrink(OffsetSkeleton.java:249)
     at main.Main.main(Main.java:33)

Looking through debug, I found that LoopL<Corner> input was actually a 
LoopL<Edge>, which was odd. I'd say that ought to be checked somehow but 
I know fuck all about generics. However if you look at 
OffsetSkeleton.shrink you'll notice the LoopL<Edge> in is indeed being 
passed into CornerClone as though it were a LoopL<Corner>.

In your regular Skeleton I noticed the SetupForEdges method and comment, 
and rightly guessed that shrink needed a stopgap as well. A copy/paste 
of that method's body into shrink fixed it for me, and it's now running 
properly.

Just thought you should know. This is the only robust Java 
implementation of inset shapes I've found on the whole internet, and I 
hate installing CGAL/Boost for little things like this.

-Nick Parker
```

Original issue reported on code.google.com by `nick.par...@gmail.com` on 4 Dec 2014 at 1:53

Attachments:
* [Main.java](https://storage.googleapis.com/google-code-attachments/campskeleton/issue-1/comment-0/Main.java)

**Comment by twak** [comment]
Finally got around to fixing this daft generics bug - OffsetSkeleton.shrink wasn't used in any of the examples, so it wasn't noticed...
